version: '2'
services:
  ns:
    container_name: sns
    build: ./
    volumes:
      - ./datasets/:/ns/datasets
      - ./paramfiles/:/ns/paramfiles
      - ./outfiles/:/ns/outfiles
    environment:
      PARAM: "default.txt"
      TIMEOUT: 30
    command: n005w4_0_1-2-3-3
