version: '2'
services:
  ns:
    container_name: dns
    build: ./
    volumes:
      - ./datasets/:/ns/datasets
      - ./outfiles/:/ns/outfiles
    #command: -i n005w4_0_1-2-3-3 -s 22-36-96-5
    entrypoint: ./scripts/testSolvingTime.sh
